AC: ac.cpp Display.cpp Display.h
	g++ -std=gnu++11 -O3  ac.cpp -o AC -lOpenCL -lopencv_core -lopencv_highgui -I/usr/local/cuda/include/ -L/usr/local/cuda/targets/x86_64-linux/lib/ -L/usr/local/cuda/lib64/

clean:
	rm -rvf AC *.zip
